version: "3.9"

services:
  sso-app:
    container_name: sso-app
    depends_on: [ sso-postgres ]
    build:
      context: .
      dockerfile: .docker/sso-app.Dockerfile
    ports:
      - "8080:8080"
      - "8082:8082"
    profiles:
      - infra
    environment:
      SSO: "UrO_9D]gJxJZ$97"
    networks:
      - net
  sso-postgres:
    container_name: sso-postgres
    image: postgres:15.3
    environment:
      POSTGRES_DB: "sso-postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    profiles:
      - infra
    networks:
      - net
  sso-integration-tests:
    container_name: sso-integration-tests
    build:
      context: .
      dockerfile: .docker/integration-tests.Dockerfile
    environment:
      BASE_URL: "http://sso-app:8080"
      MOCK_BASE_URL: "http://wiremock:8080"
      DB_HOST: "sso-postgres"
    profiles:
      - tests
    networks:
      - net
  wiremock:
    container_name: wiremock
    image: wiremock/wiremock:2.32.0
    ports:
      - "3001:8080"
    volumes:
      - ./wiremock/test-server:/home/wiremock
    profiles:
      - infra
    networks:
      - net
networks:
  net:
