name: Integration tests run
run-name: ${{ github.ref }} is merging in ${{ inputs.deploy_target }}
on: [pull_request]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running integration tests"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-qemu-action@v1
      - run: |
          ./run-app-local.sh
        name: Build app and infra
      - run: |
          ./run-test.sh
        name: Run tests
