name: Integration tests run
run-name: ${{ github.ref }} is merging in ${{ inputs.deploy_target }}
on: [pull_request]
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running integration tests"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-qemu-action@v1
      - run: |
          docker-compose -f docker-compose-local.yml down --remove-orphans -v &&
          docker-compose -f docker-compose-local.yml --profile infra build &&
          docker-compose -f docker-compose-local.yml --profile infra up
        name: Build app and infra
      - name: Sleep Action
        uses: juliangruber/sleep-action@v2.0.0
        with:
          time: 20s
      - run: |
          docker-compose -f docker-compose-local.yml --profile tests build &&
          docker-compose -f docker-compose-local.yml --profile tests up
        name: Run tests
